import { Inter } from 'next/font/google';
import CheckCircleIcon from '@mui/icons-material/CheckCircle';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'Checkout Page',
    description: 'Generated by create next app',
}

export default function CheckoutLayout({ children }) {
    return (
        <div className='w-full'>
            <div className='w-full border-b border-1 border-gray-300'>
                <div className='w-full lg:w-[1380px] gap-8 bg-white p-4 mx-auto'>
                    <img 
                        src='/img/logo/sphere/logo.svg'
                        className='h-12'
                    />
                </div>
            </div>
            <div className='flex flex-col lg:flex-row w-full lg:w-[1380px] gap-8 bg-white p-4 mx-auto'>
                <div className='flex items-center w-full lg:w-1/2'>
                    {children}
                </div>
                <div className='flex flex-col items-start w-full lg:w-1/2'>
                    <h1 className='text-[20px] lg:text-[36px] font-bold'>Over 100,000 savy consumers trust Sphere News to deliver reliable & unbiased news</h1>
                    <div className='flex flex-col gap-4 my-12'>
                        <div className='flex flex-row gap-2'>
                            <CheckCircleIcon className="text-[#0B70D1]"/>
                            <span>Bias raing: understand what you read</span>
                        </div>
                        <div className='flex flex-row gap-2'>
                            <CheckCircleIcon className="text-[#0B70D1]"/>
                            <span>A reliable news platform</span>
                        </div>
                        <div className='flex flex-row gap-2'>
                            <CheckCircleIcon className="text-[#0B70D1]"/>
                            <span>30-day money-back guarantee</span>
                        </div>
                    </div>
                    <img 
                        src='/img/others/peri-section-1.png'
                        className='p-12 bg-[#EBF3F6]'
                    />
                </div>
            </div>
        </div>
    )
}
  