export const list = [
    "Nedra Fritsch",
    "Jayce Toy",
    "Collin Pfannerstill III",
    "Corrine Kirlin",
    "Ena Lebsack",
    "Sasha McLaughlin",
    "Fausto Koch",
    "Willa Kiehn",
    "Gussie Rodriguez",
    "Jon Prohaska",
    "Bailee Hand",
    "Cristobal Bernier",
    "Letha Nienow",
    "Conner Lowe",
    "Cloyd Raynor",
    "Eveline Abbott",
    "Darwin Rolfson",
    "Paul Anderson",
    "Reina Graham",
    "Dr. Natalia Kunde",
    "Jerome Raynor",
    "Della Dickens",
    "Joyce Gleason",
    "Stephany Bayer",
    "Tavares Watsica",
    "Imelda Swift",
    "Wilhelmine Deckow DVM",
    "Sabrina Dare",
    "Hildegard Langworth",
    "Trevion Dooley",
    "Norwood Lind",
    "Holly Jacobs",
    "Laverne Hammes",
    "Kayla Lebsack",
    "Devante Yost",
    "Maymie Brekke DVM",
    "Jack Lakin",
    "Sigrid Collins",
    "Giovanni McCullough",
    "Evangeline Schultz",
    "London Johnson",
    "Ms. Aurore Bernhard",
    "Rico Conn MD",
    "Lucious Gulgowski",
    "Elwin Reilly",
    "Tomasa Leannon",
    "Eloy Howe",
    "Bo Fritsch",
    "Duane Lind",
    "Richmond Mitchell",
    "Missouri Weissnat",
    "Elias Hackett",
    "Rex Quigley V",
    "Sidney Kuphal",
    "Lonnie Emard",
    "Maximillian Stehr V",
    "Kendall Ullrich",
    "Adeline Hintz",
    "Jody Streich DDS",
    "Ms. Pete Cole",
    "Dario Kub",
    "Lorenz Fahey",
    "Alicia Gutmann",
    "Alexie Ryan",
    "Addison Aufderhar",
    "Leila Kassulke",
    "Clemens Weissnat",
    "Francisco Waters",
    "Ruthie Kiehn",
    "Alba Hintz Jr.",
    "Merle Nicolas",
    "Hiram Kuvalis",
    "Audra Hodkiewicz",
    "Adelle Parisian III",
    "Sydni Mayert",
    "Monserrate Kilback",
    "Elisabeth Bruen",
    "Samson Berge",
    "Lionel Gutmann",
    "Rhiannon Streich"
  ];
  