import { Inter } from 'next/font/google';
import Button from '@mui/material/Button';
import ArrowForwardIcon from '@mui/icons-material/ArrowForward';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'Login Page',
    description: 'Generated by create next app',
}

export default function LoginLayout({ children }) {
    return (
        <div className='flex flex-row w-full h-screen bg-white'>
            <div className='hidden md:flex items-center w-1/2 bg-gradient-to-br from-[#F9F0EB] from-60% via-[#BDC5DC] to-90% to-[#CBD3DE]'>
                <div className='flex flex-col items-center mx-auto'>
                    <div className='my-4 relative'>
                        <h3 className='text-5xl text-[#5839E3] font-bold'>Sphere News</h3>
                        <span className='bg-[#CFC7D5] text-[#AD7CC4] text-[12px] rounded-xl font-bold p-0 px-4 -top-[16px] -right-[20px] absolute'>AI</span>
                    </div>
                    <p className='my-2'>
                        Get a <span className='font-bold text-[#5839E3]'>360&deg;</span>view of the news. Powered by <span className='font-bold text-[#5839E3]'>AI.</span>
                    </p>
                    <img 
                        src='img/others/BrandCollection.png'
                        className='w-full my-2 rounded-xl'
                    />
                    <Button
                        sx={{
                            border: '1px solid #384287',
                            color: '#384287'
                        }}
                        className='items-start px-4 my-2 shadow-xl'
                    >
                        <span>GET EARLY ACCESS</span>
                        <ArrowForwardIcon 
                            sx={{
                                fontSize: 'small',
                                margin: '4px 2px'
                            }}
                        />
                    </Button>
                </div>
            </div>
            <div className='flex items-center w-full md:w-1/2'>
                {children}
            </div>
        </div>
    )
}
  